// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageSliderController from "./image_slider_controller"
application.register("image-slider", ImageSliderController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchboxController from "./searchbox_controller"
application.register("searchbox", SearchboxController)
