meta_product_name: "Downtown Vision"
meta_title: "Downtown Vision - Reimagine Your Street"
meta_description: "Reimagine your urban environment one street at a time."
meta_image: "cover_image.jpg" # should exist in `app/assets/images/`
